# Generated by Django 4.1.4 on 2023-03-25 21:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dhanriti", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="custom_url",
        ),
        migrations.AlterField(
            model_name="story",
            name="parts_order",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
