# Generated by Django 4.2.6 on 2023-10-31 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authtoken", "0003_tokenproxy"),
        ("dhanriti", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="login",
            name="token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authtoken.token",
            ),
        ),
    ]
