# Generated by Django 4.1.4 on 2023-03-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dhanriti", "0002_remove_story_custom_url_alter_story_parts_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="custom_url",
        ),
    ]
