# Generated by Django 4.2.6 on 2023-10-31 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0003_canvas_tank_funnel_flow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="canvas",
            name="old_pk",
        ),
        migrations.RemoveField(
            model_name="flow",
            name="old_pk",
        ),
        migrations.RemoveField(
            model_name="funnel",
            name="old_pk",
        ),
        migrations.RemoveField(
            model_name="login",
            name="old_pk",
        ),
        migrations.RemoveField(
            model_name="tank",
            name="old_pk",
        ),
    ]
