# Generated by Django 4.1.4 on 2023-04-05 14:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dhanriti", "0003_remove_part_custom_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalshelfstory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical shelf story",
                "verbose_name_plural": "historical Shelf Stories",
            },
        ),
        migrations.AlterModelOptions(
            name="shelfstory",
            options={"verbose_name_plural": "Shelf Stories"},
        ),
        migrations.AddField(
            model_name="shelf",
            name="cover",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelf",
            name="story_order",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
