# Generated by Django 4.1.4 on 2023-04-05 19:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dhanriti", "0004_alter_historicalshelfstory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelf",
            name="stories",
            field=models.ManyToManyField(
                through="dhanriti.ShelfStory", to="dhanriti.story"
            ),
        ),
        migrations.CreateModel(
            name="ShelfStoryTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "shelf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dhanriti.shelf"
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dhanriti.story"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Shelf Stories",
            },
        ),
    ]
