# Generated by Django 4.2.6 on 2023-10-31 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0005_alter_canvas_inflow_rate_alter_funnel_flow_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funnel",
            name="in_tank",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_tank",
                to="dhanriti.tank",
            ),
        ),
    ]
