# Generated by Django 4.2.6 on 2023-11-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0006_alter_funnel_in_tank"),
    ]

    operations = [
        migrations.AddField(
            model_name="canvas",
            name="filled",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="tank",
            name="filled",
            field=models.FloatField(default=0),
        ),
    ]
