# Generated by Django 4.1.4 on 2023-04-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dhanriti", "0006_remove_shelfstory_shelf_remove_shelfstory_story_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShelfStoryTwo",
            new_name="ShelfStory",
        ),
    ]
