# Generated by Django 4.2.6 on 2023-11-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0008_funnel_canvas"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="canvas",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flow_canvas",
                to="dhanriti.canvas",
            ),
        ),
        migrations.AlterField(
            model_name="flow",
            name="funnel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flow_funnel",
                to="dhanriti.funnel",
            ),
        ),
    ]
