# Generated by Django 4.2.6 on 2023-11-21 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0009_flow_canvas_alter_flow_funnel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="funnel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flow_funnel",
                to="dhanriti.funnel",
            ),
        ),
    ]
