# Generated by Django 4.2.6 on 2023-11-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0010_alter_flow_funnel"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="manual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="flow",
            name="meta",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
