# Generated by Django 4.1.4 on 2023-06-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhanriti', '0010_award_badge_awarded_assignedbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='claps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='reads',
            field=models.IntegerField(default=0),
        ),
    ]
