# Generated by Django 4.2.6 on 2023-11-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0011_flow_manual_flow_meta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="canvas",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flows",
                to="dhanriti.canvas",
            ),
        ),
        migrations.AlterField(
            model_name="flow",
            name="funnel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flows",
                to="dhanriti.funnel",
            ),
        ),
        migrations.AlterField(
            model_name="funnel",
            name="canvas",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funnels",
                to="dhanriti.canvas",
            ),
        ),
        migrations.AlterField(
            model_name="funnel",
            name="in_tank",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funnels",
                to="dhanriti.tank",
            ),
        ),
        migrations.AlterField(
            model_name="funnel",
            name="out_tank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_funnel",
                to="dhanriti.tank",
            ),
        ),
    ]
