# Generated by Django 4.1.4 on 2023-06-06 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dhanriti", "0011_story_claps_story_comments_story_reads"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstoryclap",
            name="clap_time",
        ),
        migrations.RemoveField(
            model_name="storyclap",
            name="clap_time",
        ),
        migrations.AddField(
            model_name="historicalstoryclap",
            name="created_at",
            field=models.DateTimeField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalstoryclap",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="historicalstoryclap",
            name="external_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="historicalstoryclap",
            name="modified_at",
            field=models.DateTimeField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="storyclap",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="storyclap",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="storyclap",
            name="external_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name="storyclap",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
