# Generated by Django 4.1.4 on 2023-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dhanriti", "0012_remove_historicalstoryclap_clap_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalfollow",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP address"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstoryclap",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP address"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstorycomment",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP address"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstorycommentlike",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP address"
            ),
        ),
    ]
