# Generated by Django 4.1.4 on 2023-06-07 03:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dhanriti', '0013_alter_historicalfollow_ip_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awarded',
            old_name='story_part',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='historicalstoryclap',
            old_name='story_part',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='historicalstorycomment',
            old_name='story_part',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='storyclap',
            old_name='story_part',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='storycomment',
            old_name='story_part',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='storyread',
            old_name='story_part',
            new_name='part',
        ),
        migrations.AddField(
            model_name='historicalstorycommentlike',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalstorycommentlike',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalstorycommentlike',
            name='external_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='historicalstorycommentlike',
            name='modified_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='storycommentlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='storycommentlike',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='storycommentlike',
            name='external_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='storycommentlike',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='storyread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='storyread',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='storyread',
            name='external_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='storyread',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
