# Generated by Django 4.1.4 on 2023-06-07 03:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dhanriti', '0015_auto_populate_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycommentlike',
            name='external_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='storyread',
            name='external_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
