# Generated by Django 4.2.2 on 2023-06-16 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhanriti', '0017_remove_historicalstorycommentlike_liked_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dhanriti.part', to_field='external_id'),
        ),
        migrations.AlterField(
            model_name='note',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dhanriti.story', to_field='external_id'),
        ),
    ]
