# Generated by Django 4.2.2 on 2023-06-26 16:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhanriti', '0019_clap_leaf_shelfleaf_rename_storycomment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='leaf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dhanriti.leaf'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='leaf_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dhanriti.part'),
        ),
    ]
