# Generated by Django 4.2.3 on 2023-07-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0021_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_setup",
            field=models.BooleanField(default=False),
        ),
    ]
