# Generated by Django 4.2.3 on 2023-07-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0022_user_account_setup"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaf",
            name="bg_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaf",
            name="meta",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="leaf",
            name="img_url",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
