# Generated by Django 4.2.2 on 2023-07-24 04:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0024_leaf_reads_alter_notification_type_leafread"),
        ("dhanriti", "0024_preset"),
    ]

    operations = []
