# Generated by Django 4.2.2 on 2023-07-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0025_merge_20230724_0406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Leaf Background"),
                    (2, "Leaf Fonts"),
                    (3, "Theme"),
                    (4, "Theme Fonts"),
                ],
                default=1,
            ),
        ),
    ]
