# Generated by Django 4.2.2 on 2023-07-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0026_alter_preset_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="preset",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="preset",
            name="premium",
            field=models.BooleanField(default=False),
        ),
    ]
