# Generated by Django 4.2.3 on 2023-07-27 16:41

from django.db import migrations, models
import dhanriti.models.users


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0027_preset_name_preset_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_settings",
            field=models.JSONField(
                default=dhanriti.models.users.default_notification_settings
            ),
        ),
    ]
