# Generated by Django 4.2.4 on 2023-08-02 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0028_user_notification_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("icon", models.TextField(blank=True, null=True)),
                ("title", models.CharField(max_length=30)),
                ("message", models.TextField(blank=True, null=True)),
                ("expires_on", models.DateTimeField(blank=True, null=True)),
                ("action", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "display_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "MOTDs",
            },
        ),
    ]
