# Generated by Django 4.2.4 on 2023-08-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0029_motd"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="closed_beta",
            field=models.BooleanField(default=False),
        ),
    ]
