# Generated by Django 4.2.2 on 2023-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0031_assignedbadge_old_pk_award_old_pk_awarded_old_pk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
