# Generated by Django 4.2.2 on 2023-08-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0032_alter_badge_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
