# Generated by Django 4.2.2 on 2023-08-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0033_alter_story_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
