# Generated by Django 4.2.2 on 2023-08-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0035_leaf_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelf",
            name="name",
            field=models.CharField(max_length=80),
        ),
    ]
