# Generated by Django 4.2.2 on 2023-08-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0036_alter_shelf_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentlike",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
