# Generated by Django 4.2.2 on 2023-08-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0037_commentlike_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="clap",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
