# Generated by Django 4.2.4 on 2023-09-05 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0042_leaf_preference_points_story_preference_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
