# Generated by Django 4.2.5 on 2023-09-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0043_invite_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="email",
            name="subject",
            field=models.TextField(default="Mail from dhanriti"),
        ),
    ]
