# Generated by Django 4.2.5 on 2023-09-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0044_email_sent_email_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preference_points",
            field=models.IntegerField(default=0),
        ),
    ]
