# Generated by Django 4.2.5 on 2023-09-15 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0045_comment_likes"),
        ("dhanriti", "0045_user_preference_points"),
    ]

    operations = []
