# Generated by Django 4.2.5 on 2023-09-24 01:41

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0046_merge_0045_comment_likes_0045_user_preference_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ip_country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
