# Generated by Django 4.2.5 on 2023-10-03 03:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0047_user_ip_country"),
    ]

    # convert "" to [] for badges_order
    def forwards_func(apps, schema_editor):
        User = apps.get_model("dhanriti", "User")
        for user in User.objects.all():
            user.badges_order = None
            user.save()

    operations = [
        migrations.AlterField(
            model_name="user",
            name="badges_order",
            field=models.CharField(default=list, null=True, blank=True),
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="award",
            name="rarity",
            field=models.IntegerField(
                choices=[
                    (1, "Common"),
                    (2, "Rare"),
                    (3, "Prestigious"),
                    (4, "Legendary"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="rarity",
            field=models.IntegerField(
                choices=[
                    (1, "Common"),
                    (2, "Rare"),
                    (3, "Prestigious"),
                    (4, "Legendary"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="badges_order",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), default=list, size=None
            ),
        ),
    ]
