# Generated by Django 4.2.5 on 2023-10-10 03:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0048_award_rarity_badge_rarity_alter_user_badges_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="badges_order",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
