# Generated by Django 4.2.6 on 2023-10-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dhanriti", "0049_alter_user_badges_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
